name: EA_DART
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: miesz <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30

dependencies:
  random_string: "^0.0.1"